### ISSUE TITLE
desktop_drop 0.5 fails to compile on Android

### ISSUE THREAD

**Issue by tmpfs** [MixinNetwork/flutter-plugins#373]
When compiling for an android target I get this error after upgrading to 0.5. The problem does not exist with 0.4.4 so I have downgraded for now.

```
/Users/muji/git/sos/gui/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: error: cannot find symbol
      flutterEngine.getPlugins().add(new one.mixin.desktop.drop.DesktopDropPlugin());
                                                               ^
  symbol:   class DesktopDropPlugin
  location: package one.mixin.desktop.drop
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 9s

```

## Expected behavior

I expect it to compile on Android.

**Version (please complete the following information):**
 - Flutter Version: 3.24.3
 - OS: MacOS compiling for Android physical device (Samsung SM325F)
 - plugin: desktop_drop: 0.5.0

**Comment by stan-at-work** [comment]
Any updates on this ?

**Comment by mauriziopinotti** [comment]
Same here on Flutter 3.27.1.

**Comment by OthmanShaker** [comment]
need a newer compile target
